- repo: https://github.com/golangci/golangci-lint
  rev: v1.23.7
  hooks:
    - id: golangci-lint
      name: golangci-lint
      description: Fast linters runner for Go.
      entry: make lint
      types: [go]
      language: golang
      pass_filenames: false
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v1.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
