linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goimports:
    local-prefixes: github.com/gelatoas
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
  misspell:
    locale: US
    ignore-words:
      - catalogue
      - catalogues
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
      - diagnostic
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - whyNoLint
  lll:
    line-length: 160
  funlen:
    lines: 100
    statements: 50
linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl
    - stylecheck
    - staticcheck
    - rowserrcheck
    - gochecknoinits
    - maligned
  #    - lll
  #    - prealloc
  #    - gochecknoglobals
  #    - gocognit
  #    - godox
  #    - gomnd
  disable-all: true
issues:
  exclude-use-default: false
  exclude-rules:
    # Almost all programs ignore errors on these functions and in most cases it's ok
    - text: 'Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked'
      linters:
        - errcheck
    # Error shadowing is a common case
    - text: 'shadow: declaration of "err" shadows declaration at line (.*)'
      linters:
        - govet
    # Transport/Endpoints req/resp assertions
    - source: '(resp|req|request|response) := (response|request|grpcReq|grpcResp|eRes|reqEndpoint).(.*)'
      linters:
        - errcheck
    # Logger
    - source: '\.Log\((.*)'
      linters:
        - errcheck
    - text: 'G104'
      linters:
        gosec
  exclude:
    - Using the variable on range scope `tc` in function literal

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.23.7 # use the fixed version to not introduce new linters unexpectedly
